### ISSUE TITLE
试了一下跑不起来，报以下错误

### ISSUE THREAD

**Issue by jypkkjj** [FinHackCN/finhack#3]
root@e4ed2f605d31:/home/new/finhack/test_project# finhack collector run --vendor=tushare
Traceback (most recent call last):
  File "/usr/local/bin/finhack", line 25, in <module>
    core.do_action()
  File "/usr/local/lib/python3.9/site-packages/finhack/core/core.py", line 175, in do_action
    method()  
  File "/usr/local/lib/python3.9/site-packages/finhack/core/loader/collector_loader.py", line 8, in run
    collector=self.klass()
TypeError: 'TushareCollector' object is not callable
Terminated
root@e4ed2f605d31:/home/new/finhack/test_project#

**Comment by woldy** [comment]
尝试更新一下版本呢？

**Comment by jypkkjj** [comment]
更新版本后正常运行了
